### PR TITLE
Framework - Explicit dropdown groups + smaller fixes

### LINKED ISSUE #816: Make `Dropdown` grouping more explicit
PR #794 introduced a feature in `Dropdown` that allows you to group dropdown-options together under  a label in the scroll-menu. How-ever, the current approach does not guarantee that options of the same group are shown together if the options array is not properly sorted before-hand, making implementation cumbersome and less intuitive.

As suggested by @rubenthoms  in https://github.com/equinor/webviz/pull/794#discussion_r1847948921, we should consider having two types of options - e.g. `DropdownOption` and `DropdownGroup`, where the group wraps a list of options.

_Naturally, this issue is only relevant if #794 is merged, but this issue should be prioritized before too many implementations make use of the current solution_

### PR DESCRIPTION
**Pull request by Anders2303**
Fixes some issues in the Dropdown framework component:
* Replaces the "group" field on dropdown options, and introduces a new `DropdownOptionGroup` type to make grouping more explicit
   * This resolves #816 
* Allows you to select options on arrow-key press even if the dropdown is closed
* Adds a max-size prop to the dropdown rectangle, so it doesnt get too wide
* Adds truncation to the dropdown list and input field to adhere to the max-width
* Fixed an issue in the `textSize` util
* Made the dropdown list use proper html tags: `<ul>` and `<li>`
* Fixed the vertical alignment of option adornments

### CODE REVIEW

File: frontend/src/lib/components/Dropdown/dropdown.tsx [hunk 1]
```diff
@@ -14,26 +14,35 @@ import { IconButton } from "../IconButton";
...
 export type DropdownOption<TValue = string> = {
     value: TValue;
     label: string;
     adornment?: React.ReactNode;
     hoverText?: string;
     disabled?: boolean;
-    group?: string;
 };
 
+type OptionOrGroup<TValue> = DropdownOption<TValue> | DropdownOptionGroup<TValue>;
```
Comment (jorgenherje) [inline frontend/src/lib/components/Dropdown/dropdown.tsx:32]: Should we stick to the typing `DropdownOption<TValue> | DropdownOptionGroup<TValue>`? As `OptionOrGroup` is not exported, the users will need to write `DropdownOption<TValue> | DropdownOptionGroup<TValue>` if building options anyways?

File: frontend/src/lib/components/Dropdown/dropdown.tsx [hunk 2]
```diff
@@ -48,57 +57,86 @@ type DropdownRect = {
...
-          type: "separator";
-          actualIndex: never;
-          content: string;
-      };
+type OptionItem<TValue> = {
+    type: "option";
+    parentGroup?: string;
+} & DropdownOption<TValue>;
+
+type SeperatorItem<TValue> = {
```
Comment (jorgenherje) [inline frontend/src/lib/components/Dropdown/dropdown.tsx:65]: Minor typo: "Seperator"->"Separator"

File: frontend/src/lib/components/Dropdown/dropdown.tsx [hunk 3]
```diff
@@ -48,57 +57,86 @@ type DropdownRect = {
...
+    type: "separator";
+    parentGroup?: never;
+} & DropdownOptionGroup<TValue>;
+
+type OptionOrSeperator<TValue> = OptionItem<TValue> | SeperatorItem<TValue>;
```
Comment (jorgenherje) [inline frontend/src/lib/components/Dropdown/dropdown.tsx:70]: Minor typo: "Seperator"->"Separator"

File: frontend/src/lib/components/Dropdown/dropdown.tsx [hunk 4]
```diff
@@ -48,57 +57,86 @@ type DropdownRect = {
...
+}
+
+function makeOptionListItems<TValue>(
+    options: OptionOrGroup<TValue>[],
+    filter?: string | null,
+    parentGroup?: string
+): OptionOrSeperator<TValue>[] {
+    return options.flatMap((option) => {
+        if (isDropdownOptionGroup(option)) {
+            const seperatorItem = {
```
Comment (jorgenherje) [inline frontend/src/lib/components/Dropdown/dropdown.tsx:91]: Minor typo: "Seperator"->"Separator"

File: frontend/src/lib/components/Dropdown/dropdown.tsx [hunk 5]
```diff
@@ -48,57 +57,86 @@ type DropdownRect = {
...
 
+    const dropdownMaxWidthOrDefault = props.dropdownMaxWidth ?? 500;
+
     const valueWithDefault = props.value ?? null;
+    const [prevValue, setPrevValue] = React.useState<TValue | null>(props.value ?? null);
+
+    const [filter, setFilter] = React.useState<string | null>(null);
+    const [prevFilter, setPrevFilter] = React.useState<string | null>(filter);
+
+    const allOptionsWithSeperators = React.useMemo(() => makeOptionListItems(props.options), [props.options]);
```
Comment (jorgenherje) [inline frontend/src/lib/components/Dropdown/dropdown.tsx:125]: Minor typo: "Seperator"->"Separator"

File: frontend/src/lib/components/Dropdown/dropdown.tsx [hunk 6]
```diff
@@ -48,57 +57,86 @@ type DropdownRect = {
...
+            // Recursively make entries for this group's items
+            const optionItems = makeOptionListItems(option.options, filter, option.label);
+
+            if (!optionItems.length) return [];
+            return [seperatorItem, ...optionItems];
         }
-    });
 
-    return optionsWithSeperators;
+        // Dont include the item if it's filtered away
```
Comment (jorgenherje) [inline frontend/src/lib/components/Dropdown/dropdown.tsx:105]: "Dont" -> "Don't"

File: frontend/src/lib/components/Dropdown/dropdown.tsx [hunk 7]
```diff
@@ -14,26 +14,35 @@ import { IconButton } from "../IconButton";
 import { Input } from "../Input";
 import { Virtualization } from "../Virtualization";
 
+export type DropdownOptionGroup<TValue = string> = {
+    label: string;
+    // ? Should groups also be allowed an adornment?
```
Comment (jorgenherje) [inline frontend/src/lib/components/Dropdown/dropdown.tsx:19]: I think it could be nice to have adornment for the group. Perhaps some dropdowns would like to have adornment only for groups, and not for options.

File: frontend/src/lib/components/Dropdown/dropdown.tsx [hunk 8]
```diff
@@ -14,26 +14,35 @@ import { IconButton } from "../IconButton";
...
-    options: DropdownOption<TValue>[];
+    options: OptionOrGroup<TValue>[];
     value?: TValue;
-    onChange?: (value: TValue) => void;
     filter?: boolean;
     width?: string | number;
     showArrows?: boolean;
     debounceTimeMs?: number;
     placeholder?: string;
+    dropdownMaxWidth?: number;
```
Comment (jorgenherje) [inline frontend/src/lib/components/Dropdown/dropdown.tsx:44]: Consider just naming it `maxWidth`?

File: frontend/src/lib/components/Dropdown/dropdown.tsx [hunk 9]
```diff
@@ -591,26 +626,22 @@ function OptionItem<TValue>(props: OptionProps<TValue>): React.ReactNode {
...
-            >
-                {props.adornment && <span className="max-w-5 max-h-5 overflow-hidden">{props.adornment}</span>}
-                {props.label}
-            </span>
-        </div>
+            {props.adornment && (
+                <div className="max-w-5 max-h-5 overflow-hidden flex-shrink-0 inline-flex">{props.adornment}</div>
+            )}
+            <span className="truncate">{props.label}</span>
+        </li>
```
Comment (jorgenherje) [inline frontend/src/lib/components/Dropdown/dropdown.tsx:633]: Keep `ml-2` for indent?

**Review by jorgenherje — CHANGES_REQUESTED** [review]
Looks very good! Just some minor comments from my side.

File: frontend/src/lib/components/Input/input.tsx [hunk 10]
```diff
@@ -174,7 +175,8 @@ export const Input = React.forwardRef((props: InputProps, ref: React.ForwardedRe
                         },
                         input: {
                             className: resolveClassNames(
-                                "h-full focus:border-indigo-500 block w-full sm:text-sm border-gray-300 outline-none"
+                                "h-full focus:border-indigo-500 block w-full sm:text-sm border-gray-300 outline-none",
+                                { "text-ellipsis": props.truncate }
```
Comment (rubenthoms) [inline frontend/src/lib/components/Input/input.tsx:179]: I think we could have this as default, i.e. remove the opt-in via props.

**Review by rubenthoms — CHANGES_REQUESTED** [review]
Looks good :+1: Some comments below.

File: frontend/src/lib/components/Dropdown/dropdown.tsx (hunk 2 above)
[the remark this answers is not in the document]
Comment (Anders2303) [reply frontend/src/lib/components/Dropdown/dropdown.tsx:65]: Renamed it to `GroupTitle`

File: frontend/src/lib/components/Dropdown/dropdown.tsx (hunk 8 above)
Comment (Anders2303) [reply frontend/src/lib/components/Dropdown/dropdown.tsx:44]: Went with `popoverMaxWidth` 👍

**Review by jorgenherje — APPROVED** [review]
Looks good to me! 👍

File: frontend/src/lib/components/Dropdown/dropdown.tsx [hunk 11]
```diff
@@ -59,74 +59,101 @@ type DropdownRect = {
...
+    if (itemList[adjustedIndex].type !== "option") {
+        if (adjustedIndex === 0) return 1;
+
+        adjustedIndex += direction;
+        adjustedIndex = _.clamp(adjustedIndex, 0, itemList.length - 1);
+    }
+
+    if (itemList[adjustedIndex].type !== "option") {
+        throw new Error("Expected option item to follow non-option item!");
+    }
```
Comment (rubenthoms) [inline frontend/src/lib/components/Dropdown/dropdown.tsx:133]: I fear this can become a pitfall as two groups following each other should preferably not cause a crash. Also, the early return in line 125 is dodging the whole check - what if there are two groups in a row at the start of the dropdown in a certain case of auto-generated data where the implementation on the consumer side is lacking functionality for filtering out empty groups? You could consider using the `lodash` `findIndex` method as it has an optional `fromIndex` parameter - thus, you would look for the next valid option from the current index. If `-1` is returned, you can start a new search from 0. With `direction === -1` you could traverse a reversed array and just adjust the index afterwards (or have a utility function doing the search and just adjust the arguments and return value accordingly).

File: frontend/src/lib/components/Dropdown/dropdown.tsx [hunk 12]
```diff
@@ -59,74 +59,101 @@ type DropdownRect = {
...
+    const popoverMaxWidthOrDefault = props.popoverMaxWidth ?? DEFAULT_POPOVER_MAX_WIDTH;
 
     const valueWithDefault = props.value ?? null;
     const [prevValue, setPrevValue] = React.useState<TValue | null>(props.value ?? null);
 
     const [filter, setFilter] = React.useState<string | null>(null);
     const [prevFilter, setPrevFilter] = React.useState<string | null>(filter);
 
-    const allOptionsWithSeperators = React.useMemo(() => makeOptionListItems(props.options), [props.options]);
+    const allOptionsWithSeparators = React.useMemo(
```
Comment (rubenthoms) [inline frontend/src/lib/components/Dropdown/dropdown.tsx:149]: Consider renaming this variable as you retired the `separator` naming scheme.

File: frontend/src/lib/components/Dropdown/dropdown.tsx [hunk 13]
```diff
@@ -182,36 +217,36 @@ export function Dropdown<TValue = string>(props: DropdownProps<TValue>) {
     }, []);
 
     React.useEffect(
-        function handleOptionsChangeEffect() {
-            function handleMouseDown(event: MouseEvent) {
+        function setupInputBlurListener() {
+            // ! The ref is *actually* the div wrapping the input, so normal "blur" is not available
```
Comment (rubenthoms) [inline frontend/src/lib/components/Dropdown/dropdown.tsx:221]: There is an `inputRef` prop that is referencing the input element. You can add a ref to that to gain control over blur etc. However, I double-checked and there was something messed up with the references - I created a PR to fix the issues: https://github.com/equinor/webviz/pull/865

File: frontend/src/lib/components/Dropdown/dropdown.tsx [hunk 14]
```diff
@@ -59,74 +59,101 @@ type DropdownRect = {
 
 type OptionItem<TValue> = {
     type: "option";
```
Comment (rubenthoms) [inline frontend/src/lib/components/Dropdown/dropdown.tsx:61]: Consider using an `enum` as a type here as it is easier to both change/maintain the code and to explicitly find all references.

File: frontend/src/lib/components/Dropdown/dropdown.tsx [hunk 15]
```diff
@@ -182,36 +217,36 @@ export function Dropdown<TValue = string>(props: DropdownProps<TValue>) {
...
                 }
             }
 
-            document.addEventListener("mousedown", handleMouseDown);
+            const dropdownInput = inputRef.current;
+            dropdownInput?.addEventListener("focusout", handleInputFocusOut);
 
-            return () => {
-                document.removeEventListener("mousedown", handleMouseDown);
+            return function removeInputBlurListener() {
```
Comment (rubenthoms) [inline frontend/src/lib/components/Dropdown/dropdown.tsx:236]: `removeInputFocusOutListener`?

File: frontend/src/lib/components/Dropdown/dropdown.tsx [hunk 16]
```diff
@@ -182,36 +217,36 @@ export function Dropdown<TValue = string>(props: DropdownProps<TValue>) {
     }, []);
 
     React.useEffect(
-        function handleOptionsChangeEffect() {
-            function handleMouseDown(event: MouseEvent) {
+        function setupInputBlurListener() {
```
Comment (rubenthoms) [inline frontend/src/lib/components/Dropdown/dropdown.tsx:220]: `...focusOut...`?

File: frontend/src/lib/components/Dropdown/dropdown.tsx [hunk 17]
```diff
@@ -325,101 +360,94 @@ export function Dropdown<TValue = string>(props: DropdownProps<TValue>) {
...
-                if (e.key === "Escape") {
-                    setDropdownVisible(false);
-                    setOptionIndexWithFocus(-1);
-                    setKeyboardFocus(false);
-                    inputRef.current?.blur();
+                // Close the dropdown
+                if (dropdownVisible && e.key === "Escape") {
+                    // FIXME: the ref is a div, so blur() isn't possible
+                    // inputRef.current?.blur();
+                    closePopover();
```
Comment (rubenthoms) [inline frontend/src/lib/components/Dropdown/dropdown.tsx:377]: See above.

**Review by rubenthoms — CHANGES_REQUESTED** [review]
The changes look really good :+1: A few comments

**Review by rubenthoms — APPROVED** [review]
LGTM :+1:
