### PR TITLE
Further improvements to distribution plot

### LINKED ISSUE #1249: DistributionPlot - Allow for independent axes

### LINKED ISSUE #1250: Distribution plot - Y Axis titles are wrong in scatterplot
Image

Image

### LINKED ISSUE #1251: DistributionPlot - Bar plot should have option to sort bars in descending order

### PR DESCRIPTION
**Pull request by HansKallekleiv**
Some further work on Distribution plot based on user feedback.

- Allow independent axes
- Allow sorting of bars by either value or key
- Fix axes titles
-
Closes #1249, closes #1250, closes #1251

### CODE REVIEW

File: frontend/src/modules/DistributionPlot/view.tsx [hunk 1]
```diff
@@ -415,22 +443,22 @@ export const View = ({ viewContext, workbenchSettings }: ModuleViewProps<Interfa
...
                         figure.addTrace(trace, rowIndex + 1, colIndex + 1);
 
-                        if (rowIndex === numRows - 1) {
-                            const patch: Partial<Layout> = {
-                                [`xaxis${cellIndex}`]: {
-                                    title: {
-                                        text: makeTitleFromChannelContent(contentX),
-                                        font,
-                                    },
+                        // if (rowIndex === numRows - 1) {
```
Comment (Anders2303) [inline frontend/src/modules/DistributionPlot/view.tsx]: Remove comment
